name: nprogress_flutter_example
description: Demonstrating the nprogress_flutter package.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  nprogress_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
