name: nprogress_flutter
description: A customizable NProgress-style top progress bar loading indicator for Flutter apps.
version: 0.0.3
homepage: https://github.com/ankitkaran99/nprogress_flutter
repository: https://github.com/ankitkaran99/nprogress_flutter
issue_tracker: https://github.com/ankitkaran99/nprogress_flutter/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
